/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risk.server;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
    }
}
