/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risk.client;

import org.junit.jupiter.api.Test;

import edu.duke.ece651.risk.shared.*;

import static org.mockito.Mockito.*;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintStream;
import java.io.StringReader;

class AppTest {
    @Test
    void test_constructor() {
      App myApp=new App();
    }
  
}













