/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risk.client;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import edu.duke.ece651.risk.shared.*;

import static org.mockito.Mockito.*;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintStream;
import java.io.StringReader;

class AppTest {
    @Test
    void test_tryConnect() {
      try{
      App myApp=new App();
      myApp.initializeApp(null, null, null, null);
      myApp.deleteJoinedRoomId(0);
      myApp.getPlayer();
      myApp.getMessenger();
      myApp.setListener(null);
      myApp.tryConnect("localhost");
    } catch (Exception e) {
    }
    }
  @Test
    void test_selectTerritory() {
      try{
        App myApp=new App(null,null,null,null);
      myApp.trySelectTerritory(null);
    } catch (Exception e) {
    }
    }
  @Test
    void test_checkIn() {
      try{
        App myApp=new App(null,null,null,null);
      myApp.checkIn();
    } catch (Exception e) {
    }
    }
  @Test
    void test_requestLeave() {
      try{
        App myApp=new App();
      myApp.initializeApp(null, null, null, null);
      myApp.requestLeave();
    } catch (Exception e) {
    }
    }
  @Test
    void test_receiveMessage() {
      try{
        App myApp=new App(null,null,null,null);
      myApp.receiveMessage();
    } catch (Exception e) {
    }
    }
  @Test
    void test_sendMessage() {
      try{
        App myApp=new App(null,null,null,null);
      myApp.sendMessage(null);
    } catch (Exception e) {
    }
    }
  @Test
    void test_tryLogin() {
      try{
        App myApp=new App(null,null,null,null);
      myApp.tryLogin(null, null);
    } catch (Exception e) {
    }
    }
  @Test
    void test_tryJoinRoom() {
      try{
        App myApp=new App(null,null,null,null);
      myApp.tryJoinRoom(0);
    } catch (Exception e) {
    }
    }
  @Test
    void test_checkGUIUpdate() {
      try{
        App myApp=new App(null,null,null,null);
        myApp.checkGUIUpdate();
        }
      catch (Exception e) {}
    }
}